### ISSUE TITLE
"&" doesn't work as expected in `:not()` in mixin

### ISSUE THREAD

**Issue by th0r** [sass/sassc-ruby#165]
`sassc-ruby v2.2.1`

Sass code:
```scss
@mixin test {
  & &__elem:not(&__elem_selected) {
    color: red;
  }
}

.foo {
  @include test;
}

.bar {
  @include test;
}
```

Compiled CSS:
```css
.foo .foo__elem:not(.foo__elem_selected) {
  color: red; }

.bar .bar__elem:not(.foo__elem_selected) {
  color: red; }
```

Expected CSS:
```css
.foo .foo__elem:not(.foo__elem_selected) {
  color: red; }

.bar .bar__elem:not(.bar__elem_selected) {
  color: red; }
```
