### ISSUE TITLE
Empty nested selector creates repeat of parent selector

### ISSUE THREAD

**Issue by Convincible** [sass/sassc-ruby#221]
In sassc 2.4.0 the following code with a stray comma:

```scss
.parent {
   .child1, .child2, {
      font: Serif;
   }
}
```

will output:

```css
.parent .child1, .parent .child2, .parent { font: Serif }
```

Note the repetition of `.parent` on its own. This behaviour is different to sass 2.2.0 in which the errant comma would be ignored, leading to the output:

```css
.parent .child1, .parent .child2 { font: Serif }
```

The older output is more natural and expected, as the use-case for "comma, nothing" to be interpreted as "repeat the parent selector" seems to me nonexistent.
