### ISSUE TITLE
Incomatible behaviour when using :not + @extend

### ISSUE THREAD

**Issue by kml** [sass/sassc-ruby#44]
I have file:
```css
.demo { color: #000000; }
a:not(.demo) { color: #ffffff; }
#div1 { input[type=submit] { @extend .demo; } }
```

When using sass (gem install sass) or sassc (brew install sassc) from console
sass -v # Sass 3.4.22 (Selective Steve)
sassc -v # sassc: 3.3.0, libsass: 3.3.2, sass2scss: 1.0.5
it generates:
```css
.demo, #div1 input[type=submit] { color: #000000; }
a:not(.demo) { color: #ffffff; }
```
But from rails application using sassc-rails it generates different selector,
which is ignored by Firefox:
```ruby
SassC::VERSION # => "1.9.0" (latest)
RUBY_DESCRIPTION # "ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]"
input_scss = File.read(File.expand_path("~/extend-bug.scss"))
SassC::Engine.new(input_scss).render
```

```css
.demo, #div1 input[type=submit] {
  color: #000000; }

a:not(.demo, #div1 input[type=submit]) {
  color: #ffffff; }
```
For now I'm going back to sass-rails.
Is that a bug? Can I give some more data that will help diagnose the problem?
