### ISSUE TITLE
Error: File to import not found or unreadable

### ISSUE THREAD

**Issue by mttdffy** [sass/sassc-ruby#79]
As of 1.12.0 I am seeing errors like this:

```
ActionView::Template::Error: Error: File to import not found or unreadable: /opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/normalize-rails-4.1.1/vendor/assets/stylesheets/normalize-rails/normalize.
        on line 1 of ../../../../../../opt/rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/normalize-rails-4.1.1/vendor/assets/stylesheets/normalize-rails.scss
```

Downgrading to 1.11.4 I no longer saw this issue.

**Comment by tubbo** [comment]
the issue seems to be related to this: https://github.com/sass/libsass/releases/tag/3.5.3

@xzyfer ^

**Comment by yjukaku** [comment]
```
rails generate new test-sassc
cd test-sassc
bundle
#... add sassc gem via gem 'sassc', '1.12.0'
#... add sassc-rails via gem 'sassc-rails'
```
```scss
# in app/assets/stylesheets/application.scss
@import "vend"
```

```css
/* vendor/assets/stylesheets/vend.css */
.something{
  color: red;
}
```

## With `gem 'sassc', '1.11.4'`
```
bundle exec rake assets:precompile
# ... successfully creates public/assets/application.css
```
```css
/* public/assets/application.css */
.something { 
  color: red;
}

```

## With `gem 'sassc', '1.12.0'`

```
bundle exec rake assets:precompile
rake aborted!
SassC::SyntaxError: Error: File to import not found or unreadable: /Users/whatever/test-sassc/vendor/assets/stylesheets/vend.
        on line 17 of app/assets/stylesheets/application.scss
>> @import "vend"
```
